<?php
/**
 * Page cache check.
 *
 * @package ProbeSiteDoctor
 */

namespace ProbeSiteDoctor\Diagnostics\Checks\Performance;

use ProbeSiteDoctor\Diagnostics\AbstractCheck;
use ProbeSiteDoctor\Diagnostics\CategoryRegistry;
use ProbeSiteDoctor\Diagnostics\Measurement;
use ProbeSiteDoctor\Diagnostics\Result;
use ProbeSiteDoctor\Diagnostics\Severity;
use ProbeSiteDoctor\Diagnostics\Support\Loopback;

defined( 'ABSPATH' ) || exit;

/**
 * Detects full-page caching and times the server's response to itself.
 *
 * Signals: WP_CACHE with an advanced-cache.php drop-in, cache response
 * headers (from plugins, servers and CDNs), and HTML comments left by
 * common caching plugins. The homepage is requested three times so a cold
 * cache can warm up.
 */
final class PageCacheCheck extends AbstractCheck {

	private const REQUESTS = 3;

	/**
	 * Headers whose value contains "hit" when a cache served the response.
	 *
	 * @var string[]
	 */
	private const HIT_HEADERS = array(
		'x-cache',
		'x-cache-status',
		'x-proxy-cache',
		'cf-cache-status',
		'x-litespeed-cache',
		'x-srcache-fetch-status',
		'x-sucuri-cache',
		'x-kinsta-cache',
		'x-nginx-cache-status',
		'x-varnish-cache',
		'x-ac',
		'x-fastcgi-cache',
		'x-sg-cache',
	);

	/**
	 * HTML comment markers left by caching plugins.
	 *
	 * @var array<string,string>
	 */
	private const HTML_MARKERS = array(
		'WP Super Cache'   => 'generated by WP-Super-Cache',
		'WP Rocket'        => 'This website is like a Rocket',
		'W3 Total Cache'   => 'by W3 Total Cache',
		'LiteSpeed Cache'  => 'Page cached by LiteSpeed',
		'Cache Enabler'    => 'Cache Enabler by KeyCDN',
		'WP Fastest Cache' => 'WP Fastest Cache file was created',
		'Hummingbird'      => 'Hummingbird cache file',
		'Breeze'           => 'Cache served by breeze',
	);

	public function get_id(): string {
		return 'performance.page-cache';
	}

	public function get_category(): string {
		return CategoryRegistry::PERFORMANCE;
	}

	public function get_label(): string {
		return __( 'Page cache', 'probe-site-doctor' );
	}

	public function get_description(): string {
		return __( 'Detects full-page caching and measures how long the server takes to answer a request for the homepage from itself.', 'probe-site-doctor' );
	}

	public function get_measurement(): string {
		return Measurement::LOOPBACK;
	}

	public function run(): Result {
		$t = $this->thresholds(
			array(
				'good_ms'     => 600,
				'critical_ms' => 2000,
			)
		);

		$times    = array();
		$signals  = array();
		$last     = null;
		$failures = array();

		for ( $i = 0; $i < self::REQUESTS; $i++ ) {
			$response = Loopback::get();
			if ( ! $response['ok'] ) {
				$failures[] = $response['error'];
				continue;
			}
			$times[] = $response['time_ms'];
			$last    = $response;
			foreach ( $this->header_signals( $response['headers'] ) as $signal ) {
				$signals[ $signal ] = true;
			}
		}

		if ( ! $times ) {
			return $this->skipped(
				sprintf(
					/* translators: %s: Error message. */
					__( 'The server could not request its own homepage (%s). This happens when loopback requests are blocked, the site is password-protected, or it is in maintenance mode.', 'probe-site-doctor' ),
					$failures ? $failures[0] : __( 'unknown error', 'probe-site-doctor' )
				)
			);
		}

		foreach ( self::HTML_MARKERS as $plugin => $marker ) {
			if ( false !== stripos( substr( $last['body'], -4096 ), $marker ) ) {
				$signals[ sprintf( /* translators: %s: Plugin name. */ __( '%s page marker', 'probe-site-doctor' ), $plugin ) ] = true;
			}
		}

		$dropin = defined( 'WP_CACHE' ) && WP_CACHE && file_exists( WP_CONTENT_DIR . '/advanced-cache.php' );
		if ( $dropin ) {
			$signals[ __( 'advanced-cache.php drop-in with WP_CACHE enabled', 'probe-site-doctor' ) ] = true;
		}

		sort( $times );
		$median = $times[ (int) floor( count( $times ) / 2 ) ];
		$cached = ! empty( $signals );

		$data = array(
			'cache_detected'      => $cached,
			'signals'             => array_keys( $signals ),
			'median_response_ms'  => $median,
			'fastest_response_ms' => $times[0],
			'requests'            => count( $times ),
			'http_status'         => $last['status'],
		);

		$timing = sprintf(
			/* translators: %s: Milliseconds. */
			__( 'Median server response time: %s ms.', 'probe-site-doctor' ),
			number_format_i18n( $median )
		);
		$scope  = __( 'This is the time for the server to answer a request from itself. It is not a page-load time: visitor network latency, image and script downloads, and browser rendering are not included.', 'probe-site-doctor' );
		$enable = __( 'Enable full-page caching: many hosts offer it built in, or use a caching plugin. Then run the scan again.', 'probe-site-doctor' );

		if ( $median >= $t['critical_ms'] ) {
			return $this->critical(
				__( 'The server responds very slowly', 'probe-site-doctor' ),
				$timing . ' ' . ( $cached ? __( 'A page cache appears to be present but the homepage is still slow, so it may not be serving this page.', 'probe-site-doctor' ) : __( 'No page cache was detected.', 'probe-site-doctor' ) ) . ' ' . $scope,
				$cached ? __( 'Check that the cache covers the homepage and is not bypassed. Then look for slow plugins or an overloaded server.', 'probe-site-doctor' ) : $enable,
				$data
			);
		}

		if ( $cached && $median < $t['good_ms'] ) {
			return $this->good(
				__( 'Page caching is active', 'probe-site-doctor' ),
				sprintf(
					/* translators: %s: List of detected signals. */
					__( 'Detected: %s.', 'probe-site-doctor' ),
					implode( ', ', array_keys( $signals ) )
				) . ' ' . $timing . ' ' . $scope,
				$data
			);
		}

		if ( $cached ) {
			return $this->warning(
				__( 'A page cache is present, but responses are slow', 'probe-site-doctor' ),
				$timing . ' ' . __( 'Cached pages are normally served in well under a second.', 'probe-site-doctor' ) . ' ' . $scope,
				__( 'Check that the cache covers the homepage and that cache headers are not being stripped. Then look for slow plugins or limited server resources.', 'probe-site-doctor' ),
				$data
			);
		}

		return $this->result(
			$median < $t['good_ms'] ? Severity::INFO : Severity::WARNING,
			__( 'No page cache detected', 'probe-site-doctor' ),
			$timing . ' ' . ( $median < $t['good_ms']
				? __( 'Responses are currently fast without a page cache, but every visit makes WordPress build the page again.', 'probe-site-doctor' )
				: __( 'Every visit makes WordPress build the page again, and responses are slower than recommended.', 'probe-site-doctor' ) ) . ' ' . $scope,
			$enable,
			$data
		);
	}

	/**
	 * Cache signals found in response headers.
	 *
	 * @param array<string,string> $headers Lower-cased headers.
	 * @return string[]
	 */
	private function header_signals( array $headers ): array {
		$signals = array();

		foreach ( self::HIT_HEADERS as $name ) {
			if ( isset( $headers[ $name ] ) && false !== stripos( $headers[ $name ], 'hit' ) ) {
				$signals[] = $name . ': ' . $headers[ $name ];
			}
		}
		if ( isset( $headers['age'] ) && (int) $headers['age'] > 0 ) {
			$signals[] = 'age: ' . (int) $headers['age'];
		}
		if ( isset( $headers['x-cache-enabled'] ) && 'true' === strtolower( trim( $headers['x-cache-enabled'] ) ) ) {
			$signals[] = 'x-cache-enabled: true';
		}
		if ( isset( $headers['cache-control'] ) && preg_match( '/s-maxage=(\d+)/i', $headers['cache-control'], $m ) && (int) $m[1] > 0 ) {
			$signals[] = 'cache-control: s-maxage=' . (int) $m[1];
		}

		return $signals;
	}
}
